### ISSUE TITLE
Re_submit  SRS

### ISSUE THREAD

**Issue by josephfarahat** [josephfarahat/SE2018G02#1]
Dear all, 
We have several technical writing issues regarding fonts, colors, and margins. 
Also we need to add some functionalities to our system (ex: edit questions, delete it, blocking..). 
We will discuss it in details god willing tomorrow after the lecture of Control system

**Comment by MernaElhassan** [comment]
We will fix these issues and we will do the SRS in a better way. We'll meet tomorrow to talk about it.

**Comment by HMarsafy** [comment]
ok , will fix all these  technical writing issues inshaaallah.

**Comment by josephfarahat** [comment]
I have uploaded a new file with our new layout that Hassan and me did it. Please leave your comments about it here

**Comment by josephfarahat** [comment]
https://github.com/josephfarahat/SE2018G02/tree/master/Documentation/SRS

**Comment by josephfarahat** [comment]
@MernaElhassan 
![47571385_499162237245392_4846119476770373632_n](https://user-images.githubusercontent.com/36537848/49614000-ba9a4480-f9b1-11e8-834d-909deff61a24.jpg)


- [we need you to write about data analysis ]

**Comment by MernaElhassan** [comment]
Okay , I will write about this👌🏻
