### ISSUE TITLE
1st development phase

### ISSUE THREAD

**Issue by josephfarahat** [josephfarahat/SE2018G02#3]
Currently, the tasks in development are :
 1) Back-end : a) Login function (Paula)
b) Inquiry : Mirna
c) Questions/Answers : Hamza
d) Feedback ;Amir
e)  Poll Session: Beshoy and Joseph 
2) Front end : Design and implementation of  pages/  :  Yomna , Hassan and Hamed

**Comment by polarag** [comment]
1. f) File sharing (Paula)

**Comment by josephfarahat** [comment]
Tomorrow we are meeting for the integration part between the current finished php pages and their respective front end pages

**Comment by josephfarahat** [comment]
4/2 progression : we successfully integrated the home page buttons to their respective html pages, and finished the feedback function from the audience to speaker integrated fully on the website. 
tomorrow (5/2) objectives : login integration , speaker side pages integration, Inquiry and answers polls

**Comment by josephfarahat** [comment]
5/2 : We successfully finished the login integration, Inquiry, and answer polls on the audience side.
We are still working on the results page of the poll which our main objective for tomorrow 6/2.
